# Generated by Django 4.0 on 2023-08-21 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.userbio')),
                ('cadidate_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VoteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.DateTimeField(auto_now_add=True)),
                ('candidates', models.ManyToManyField(to='voteapp.candidate')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.role')),
                ('voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.election'),
        ),
    ]
