# Generated by Django 4.0 on 2023-08-22 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='votetable',
            name='candidates',
            field=models.ManyToManyField(to='voteapp.Candidate'),
        ),
    ]
