# Generated by Django 4.0 on 2023-08-24 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0004_rename_cadidate_name_candidate_candidate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.role')),
                ('voters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
