# Generated by Django 4.0 on 2023-08-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0005_votecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.role'),
        ),
    ]
