# Generated by Django 4.0 on 2023-08-26 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0006_alter_candidate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecheck',
            name='voters',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
